# Generated by Django 4.2.7 on 2023-12-15 18:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('basket', '0002_alter_basket_customer'),
        ('authentication', '0002_remove_customer_user_remove_user_groups_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Customer',
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
