# Generated by Django 4.1.13 on 2024-01-01 18:26

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('product', '0001_initial'),
        ('authentication', '0001_initial'),
        ('address', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('P', 'Pending'), ('H', 'Preparing'), ('S', 'Shipping'), ('D', 'Delivered'), ('C', 'Cancelled')], default='P', max_length=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('billing_address', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='billing_address', to='address.address')),
                ('customer', models.ForeignKey(help_text='Customer who is ordering', on_delete=django.db.models.deletion.CASCADE, to='authentication.customer')),
                ('shipping_address', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shipping_address', to='address.address')),
            ],
        ),
        migrations.CreateModel(
            name='OrderedItems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('regular_price', models.DecimalField(decimal_places=2, max_digits=6, validators=[django.core.validators.MinValueValidator(1)])),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='order.order')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='product.product')),
            ],
        ),
        migrations.AddConstraint(
            model_name='ordereditems',
            constraint=models.UniqueConstraint(fields=('order', 'product'), name='unique_product_in_order'),
        ),
    ]
