# Generated by Django 4.2.7 on 2023-12-24 21:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderdetails',
            name='order',
        ),
    ]
