# Generated by Django 4.2.7 on 2023-12-24 21:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_remove_orderdetails_order'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='user',
            new_name='customer',
        ),
    ]
