# Generated by Django 4.1.13 on 2023-12-29 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0004_remove_order_basket_items_remove_order_updated_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('P', 'Pending'), ('H', 'Preparing'), ('S', 'Shipping'), ('D', 'Delivered'), ('C', 'Cancelled')], default='P', max_length=1),
        ),
        migrations.DeleteModel(
            name='OrderDetails',
        ),
    ]
