# Generated by Django 4.2.7 on 2023-12-23 05:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mahalle', models.CharField(max_length=50)),
                ('cadde', models.CharField(max_length=50)),
                ('sokak', models.CharField(max_length=50)),
                ('apartman', models.CharField(max_length=50)),
                ('daire', models.CharField(max_length=50)),
                ('semt', models.CharField(max_length=50)),
                ('sehir', models.CharField(max_length=50)),
                ('country', django_countries.fields.CountryField(max_length=2)),
                ('post_code', models.CharField(max_length=10)),
                ('address_type', models.CharField(choices=[('B', 'Billing'), ('S', 'Shipping')], max_length=1)),
                ('default', models.BooleanField(default=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
