# Generated by Django 4.1.13 on 2023-12-31 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('address', '0003_address_address_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='address_name',
            field=models.CharField(max_length=50),
        ),
    ]
