# Generated by Django 4.2.7 on 2023-12-17 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='is_active',
            new_name='is_featured',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='is_home',
            new_name='is_offer',
        ),
        migrations.AddField(
            model_name='product',
            name='discount_percentage',
            field=models.PositiveIntegerField(default=0, error_messages={'name': {'max_length': 'The discount percentege must be between 0 and 99'}}, help_text='Maximum 99.99'),
        ),
        migrations.AddField(
            model_name='product',
            name='is_slide',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='product',
            name='discount_price',
            field=models.DecimalField(decimal_places=2, error_messages={'name': {'max_length': 'The price must be between 0 and 999.99.'}}, help_text='Maximum 999.99', max_digits=8),
        ),
        migrations.AlterField(
            model_name='product',
            name='regular_price',
            field=models.DecimalField(decimal_places=2, error_messages={'name': {'max_length': 'The price must be between 0 and 999.999.99.'}}, help_text='Maximum 999.99', max_digits=8),
        ),
    ]
