# Generated by Django 4.1.13 on 2024-01-03 10:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_productimage'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productimage',
            old_name='extra_image',
            new_name='image',
        ),
    ]
