# Generated by Django 4.2.7 on 2023-12-04 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_orderwithoutmembership_delete_order_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderwithoutmembership',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
