# Generated by Django 4.2.7 on 2023-12-17 00:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_rename_is_active_product_is_featured_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='discount_price',
        ),
    ]
