# Generated by Django 4.2.7 on 2023-12-14 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_remove_product_image_productimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='productpic'),
        ),
        migrations.DeleteModel(
            name='ProductImage',
        ),
    ]
