# Generated by Django 4.2.7 on 2023-12-17 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_product_discount_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='discount_percentage',
            field=models.PositiveIntegerField(blank=True, default=0, error_messages={'name': {'max_length': 'The discount percentege must be between 0 and 99'}}, help_text='Maximum 99.99'),
        ),
    ]
