# Generated by Django 4.2.7 on 2023-12-17 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0007_alter_product_discount_percentage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='regular_price',
            field=models.DecimalField(decimal_places=2, error_messages={'name': {'max_length': 'The price must be between 0 and 999.999.99.'}}, help_text='Required-Maximum 999.999,99', max_digits=8),
        ),
    ]
