# Generated by Django 4.2.7 on 2023-12-15 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0014_remove_product_category_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='categories',
            field=models.ManyToManyField(blank=True, default=4, to='product.category'),
        ),
    ]
