# Generated by Django 4.2.7 on 2023-12-15 18:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authorization', '0001_initial'),
        ('basket', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basket',
            name='customer',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='authorization.customer'),
        ),
    ]
